-- SELECT SUM(total) AS "Total spent money" FROM receipts;
------------------------------------------------------------------------------------------
-- SELECT SUM(total) AS "Total spent money", DATE_TRUNC('month', receipt_date) AS "Month" 
--     FROM receipts 
--     GROUP BY DATE_TRUNC('month', receipt_date);
------------------------------------------------------------------------------------------
-- SELECT SUM(p.price) AS "Total money spent",
--     c.name AS "Category name"
-- FROM purchases p
--     INNER JOIN products pr ON pr.product_id = p.product_id
--     INNER JOIN categories c ON c.category_id = pr.category_id
-- GROUP BY c.name
-- ORDER BY "Total money spent" DESC;