-- PASSWORD WAS LEFT ONLY FOR DOCUMENTATION PURPOSES
CREATE USER readonly_user WITH PASSWORD 'example-password';

GRANT CONNECT ON DATABASE receipts_project TO readonly_user;
GRANT USAGE ON SCHEMA public TO readonly_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly_user;
